# Generated by Django 5.2.14 on 2026-05-11 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено (мягкое)')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № двигателя')),
                ('transmission_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № трансмиссии')),
                ('driving_axle_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № ведущего моста')),
                ('steerable_axle_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № управляемого моста')),
                ('supply_contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='№ договора поставки')),
                ('supply_contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('shipment_date', models.DateField(db_index=True, verbose_name='Дата отгрузки с завода')),
                ('recipient', models.CharField(blank=True, max_length=255, null=True, verbose_name='Грузополучатель')),
                ('operation_address', models.TextField(blank=True, null=True, verbose_name='Адрес эксплуатации')),
                ('equipment_options', models.TextField(blank=True, null=True, verbose_name='Комплектация')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_machines', to='organizations.organization', verbose_name='Клиент')),
                ('driving_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.drivingaxlemodel', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.enginemodel', verbose_name='Модель двигателя')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_machines', to='organizations.organization', verbose_name='Сервисная компания')),
                ('steerable_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.steerableaxlemodel', verbose_name='Модель управляемого моста')),
                ('technique_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.techniquemodel', verbose_name='Модель техники')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.transmissionmodel', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['-shipment_date'],
            },
        ),
    ]
