# Generated by Django 5.2.14 on 2026-05-11 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('organizations', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено (мягкое)')),
                ('maintenance_date', models.DateField(db_index=True, verbose_name='Дата проведения ТО')),
                ('operating_hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Наработка, м/час')),
                ('work_order_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(blank=True, null=True, verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='machines.machine', verbose_name='Машина')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.maintenancetype', verbose_name='Вид ТО')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'ТО',
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
