# Generated by Django 5.2.14 on 2026-05-11 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('organizations', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено (мягкое)')),
                ('failure_date', models.DateField(db_index=True, verbose_name='Дата отказа')),
                ('operating_hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts_used', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('restoration_date', models.DateField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Закрыта')], default='open', max_length=20, verbose_name='Статус')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.failurenode', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='machines.machine', verbose_name='Машина')),
                ('restoration_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.restorationmethod', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['-failure_date'],
            },
        ),
    ]
