# Generated by Django 6.0.5 on 2026-05-15 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_buyer',
            field=models.BooleanField(default=False, help_text="Фигурирует в поле 'Покупатель' в данных завода", verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Конечный потребитель / эксплуатант техники', verbose_name='Клиент (грузополучатель)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_service_company',
            field=models.BooleanField(default=False, help_text='Выполняет ТО и ремонтные работы', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название организации'),
        ),
    ]
